### ISSUE TITLE
Address open tasks for Part 1

### ISSUE THREAD

**Issue by j-i-l** [t4d-gmbh/working-with-git#26]
Identify what needs to be adapted and what needs to be added to https://github.com/t4d-gmbh/working-with-git to cover the learnings defined for this part:

https://github.com/t4d-gmbh/using-git-in-academia?tab=readme-ov-file#1-part-working-with-git

- [x] t4d-gmbh/working-with-git#20 
- [x] t4d-gmbh/working-with-git#21 
- [x] t4d-gmbh/working-with-git#22 
- [x] t4d-gmbh/working-with-git#23
- [x] t4d-gmbh/working-with-git#24
- [x] t4d-gmbh/working-with-git#25

We also need to:

- [x] t4d-gmbh/using-git-in-academia#11
